version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: endowcast
      POSTGRES_PASSWORD: development_password
      POSTGRES_DB: endowcast_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
